COOKIE = b"NATT"
PORT = 6545
UDP_SOCKET_TIMEOUT = 1
SERVER_REQUEST_PROBES = 10
ADDR_WAIT_TIME = 3
HELLO_PACKET = COOKIE + b"HELLO"
HELLO_PACKETS_COUNT = 1
KEEPALIVE_SEND_TIME = 15
KEEPALIVE_PACKET = COOKIE + b"KEEPALIVE"
OPERATION_TIMEOUT = 3
SERVER_WORKERS = 10
LOCAL_CONNECTION_TIMEOUT = 1

